### ISSUE TITLE
大佬,可不可以放在gitee上面呢?实在拉取不下来啊

### ISSUE THREAD

**Issue by yy755964539** [wxiaoqi/Spring-Cloud-Platform-UI#1]
大佬,可不可以放在gitee上面呢?实在拉取不下来啊
大佬,可不可以放在gitee上面呢?实在拉取不下来啊
大佬,可不可以放在gitee上面呢?实在拉取不下来啊
大佬,可不可以放在gitee上面呢?实在拉取不下来啊
大佬,可不可以放在gitee上面呢?实在拉取不下来啊
大佬,可不可以放在gitee上面呢?实在拉取不下来啊

**Comment by wxiaoqi** [comment]
已放，https://gitee.com/geek_qi/Cloud-Platform-UI-V2
